### ISSUE TITLE
Need FAQ for event

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#20]
Can someone put together basic FAQ for the website on what's needed to get up and running and what to expect? Inspiration here: http://nodeschool.io/toronto/

* what to bring (laptop)
* what to download (node.js, npm, learnyounode)
* what to expect (rough schedule, agenda)

And any other relevant information that would have been good for attendees to know based on last event

**Comment by emkay** [comment]
Here is the email I sent out for the first one we did:

Hi all,

If you are receiving this email it means you have a ticket for NodeSchool LA. 

First off if you cannot attend please cancel your ticket so that we can maximize the amount of people that can go. We are really short on space and sold out of tickets pretty quickly. Please don’t flake without canceling your ticket.

The event will be this Saturday November 8th and starting at 10am and going on until 2pm. The host is M-Go. The address is  3534 Hayden Ave;  Culver City, CA 90232. Please park on the street and not in the lot. 

Some homework you can do before Saturday morning: 

1. Please make sure you have Node.js downloaded and installed: Go to http://nodejs.org/ and click on the “Install” button.  
2. Browse http://nodeschool.io/#workshopper-list and take a look at what you would like to work on. If possible you can also install it.

If you have problems doing either of those, or are having trouble picking what workshops you want to work on, don’t worry too much about it. We can help you out on Saturday morning. 

We will be having lunch there so if you have any diet restrictions please let me know so we can plan for it.

Please email me with any other questions.

Thanks!

-- 
Michael Matuzak
@mmatuzak

**Comment by d48** [comment]
Awesome, great note about the ticket canceling and the homework

**Comment by d48** [comment]
I'll be sending out something like this the week of. What are you guys using for newsletter/email blasts?

We should get a concise version of this on the website too somewhere. @jcblw , take what @emkay  posted for list items in consideration for the design you did on #27  :boom:

**Comment by d48** [comment]
I updated the website with this information. Thanks!
