### ISSUE TITLE
Add "Want to Sponsor an Event?" section

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#50]
In the attempt to start booking both hosts and event sponsors for upcoming events, it would be ideal to have a section denoting that this group is always looking for sponsors. Any inquiries can contact this email: nodeschool@js.la

_Action_
We need someone to update the website to add this section, with some welcoming and terse verbiage with link to contact for inquiries.

Thank you!

**Comment by rouzbeh84** [comment]
We have this with contribute.js.la now but not sure it applies to nodeschool...

**Comment by d48** [comment]
i imagine it can be similar. right now js.la covers sponsoring for it unless it has changed, cc'ing @davidguttman. It's nice for other people/companies to come in and offer sponsorship to cover things like food and space

**Comment by ashwell** [comment]
Yeah, I think we'd be better off leaving contribute.js.la to just js.la stuff for now. I wouldn't be opposed to extending that site to include forms for nodeschool tho.

But to fill you in @rouzbeh84 we kinda stopped looking for sponsors because js.la can normally cover the food costs, and we don't look for hosts because we have gotten good results with having it at the same location every month.

That being said, I would think it would be great to be more open to direct nodeschool sponsorship and varying the host location. The only problem is that takes time and effort, something a lot of us on the team just don't have enough of.

but adding a section to the site about it would be a good start / short term option.

**Comment by rouzbeh84** [comment]
sounds good to me!
