### ISSUE TITLE
Mentor roll call for September 3, 2016 event at Code District

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#87]
Who would like to help mentor for this event?

- [x] @d48 
- [x] @ashwell 
- [x] @Jahosh 
- [x] @davidguttman 
- [ ] you?

**Comment by ashwell** [comment]
I should be around!

**Comment by svincent** [comment]
I'm interested but I've never attended a NodeSchool let alone mentored one before.

I'm a frontend engineer and spend most of my day in JS-land. I've done a little Node work but mostly dev servers, gulp scripting, and a little bit of work with Node streams. 

Do you happen to have a list of the Top 5 most common NodeSchool tutorials or some such? I'd be happy to do my homework on this to make sure I've got common issues resolved by September 3rd.

**Comment by ashwell** [comment]
Hey @svincent thanks for the inquiry! If you feel yourself to be a mentor in the everyday javascript world you shouldn't have trouble mentoring at a Nodeschool event.

The biggest help to mentoring a Nodeschool event is being familiar with the workshoppers. You can check out list of them on the [Nodeschool Site](http://nodeschool.io/#workshopper-list). (the definition of [workshopper](http://nodeschool.io/#workshoppers) is just above the list)

I would suggest trying one of the workshoppers that seems interesting to you, so you get know know how they are structured. Also if you want to mentor you should be familiar with everything covered in the Javascripting and learnyounode workshoppers. Some other popular ones are, stream-adventure, Functional Javascript, Promise It Won't Hurt, and Scope Chains & Closures.

But as always with mentoring of any kind its not about giving answers but giving hints so that the mentee discovers the answer on their own.

If you feel confident then we would love to have you as a mentor, if not feel free to come as an attendee to get the lay of the land and maybe come back as a mentor the following month!

**Comment by svincent** [comment]
I think I'll join as a attendee and see how that goes 👍

**Comment by adamcee** [comment]
Hi!

I'm interested in possibly mentoring at the upcoming Nodeschool LA on Sept 3. I have experience working with node.js at a startup, and Angular.js in another role. And I have past experience teaching, and really enjoy it. What are you looking for in a mentor, and what is involved? What's the general experience level of mentors and mentees?

Sincerely
Adam

**Comment by ashwell** [comment]
Hey @adamcee thanks for the interest! I could write up a little explainer, but the SF Nodeschool group has already written some great stuff about Nodeschool. Most notably [this wiki page](https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice) has a lot of great advice and information about mentoring an event.

**Comment by ashwell** [comment]
In short to answer your questions directly @adamcee,

* Anyone with a great attitude who is willing to volunteer their time and has a good bit of JavaScript experience is welcome.
* As a mentor you will help the attendees when they get stuck or ask for help. Basically you are an on-demand programming pair. The event is **not** a traditional lecture based classroom setting, everyone is encouraged to collaborate and help others as needed or desired. 
* Most mentors are upper mid to senior level developers but there are no requirements or anything. There are always a few attendees that are brand new to programming or javascript so don't feel like you have to be an expert. Mentor experience can really vary, anywhere from new to programming, to new to JavaScript, to looking to learn advanced JavaScript techniques like Functional Programming.

**Comment by d48** [comment]
thanks guys. Let me know if you want to be added to the mentor list. See everyone in about a week

**Comment by jcblw** [comment]
@Jahosh you still thinking about mentoring?

**Comment by Jahosh** [comment]
I am, signing up now...

**Comment by d48** [comment]
👍👊

**Comment by d48** [comment]
see you guys later today. Posted day schedule and info here: https://github.com/nodeschool/los-angeles/issues/90
